---

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y tcl8.5 tcl8.5-dev

language: rust

rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly

  fast_finish: true

cache: cargo
